# This is a basic workflow to help you get started with Actions

name: Prerelease

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on: [workflow_dispatch]

# default environment variables
env:
  TARGET: 'win'
  ARTIFACT_FILTER: '*.exe'
  ARTIFACT_NAME: 'HstWB Imager 0.1.0 Windows.exe'
  ARTIFACT_NAME_WINDOWS: 'HstWB Imager 0.1.0 Windows.exe'
  ARTIFACT_NAME_MACOS: 'HstWB Imager 0.1.0 macOS.dmg'
  ARTIFACT_NAME_LINUX: 'HstWB Imager 0.1.0 Linux.AppImage'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win-x64
          - os: macos-latest
            target: osx-x64
          - os: ubuntu-latest
            target: linux-x64
          - os: ubuntu-latest
            target: linux-arm64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set version
        working-directory: ./src
        shell: pwsh
        run: |
          "BUILD_VERSION=0.9.{0}" -f (git rev-list --count $env:GITHUB_REF) >> $env:GITHUB_ENV
          "BUILD_VERSION_SHA={0}" -f (git log --pretty=format:'%h' -n 1 $env:GITHUB_REF) >> $env:GITHUB_ENV

      - name: Show version
        shell: pwsh
        run: |
          "BUILD_VERSION: ${{ env.BUILD_VERSION }}"
          "BUILD_VERSION_SHA: ${{ env.BUILD_VERSION_SHA }}"

      - name: Set Windows 64-bit release
        shell: pwsh
        run: |
          "TARGET=win-x64;x64" >> $env:GITHUB_ENV
          "ELECTRON_ARCH=x64" >> $env:GITHUB_ENV
          "ARTIFACT_FILTER=*.exe" >> $env:GITHUB_ENV
          "ARTIFACT_NAME=hstwb.imager.artifact-file.win-x64" >> $env:GITHUB_ENV
          $artifactName='HstWB Imager ${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }} Windows 64-bit.exe'
          "$artifactName" > hstwb.imager.artifact-name.win-x64.txt
          "ARTIFACT_FILENAME=$artifactName" >> $env:GITHUB_ENV
          "HstWB Imager v${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }}" > hstwb.imager.release-name.txt
        if: matrix.os == 'windows-latest'

      - name: Set macOS 64-bit release
        shell: pwsh
        run: |
          "TARGET=osx-x64;x64" >> $env:GITHUB_ENV
          "ELECTRON_ARCH=x64" >> $env:GITHUB_ENV
          "ARTIFACT_FILTER=*.dmg" >> $env:GITHUB_ENV
          "ARTIFACT_NAME=hstwb.imager.artifact-file.osx-x64" >> $env:GITHUB_ENV
          $artifactName='HstWB Imager ${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }} macOS 64-bit.dmg'
          "$artifactName" > hstwb.imager.artifact-name.osx-x64.txt
          "ARTIFACT_FILENAME=$artifactName" >> $env:GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Set Linux 64-bit release
        shell: pwsh
        run: |
          "TARGET=linux-x64;x64" >> $env:GITHUB_ENV
          "ELECTRON_ARCH=x64" >> $env:GITHUB_ENV
          "ARTIFACT_FILTER=*x64.AppImage" >> $env:GITHUB_ENV
          "ARTIFACT_NAME=hstwb.imager.artifact-file.linux-x64" >> $env:GITHUB_ENV
          $artifactName='HstWB Imager ${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }} Linux 64-bit.AppImage'
          "$artifactName" > hstwb.imager.artifact-name.linux-x64.txt
          "ARTIFACT_FILENAME=$artifactName" >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'linux-x64'

      - name: Set Linux ARM64 release
        shell: pwsh
        run: |
          "TARGET=linux-arm64;arm64" >> $env:GITHUB_ENV
          "ELECTRON_ARCH=arm64" >> $env:GITHUB_ENV
          "ARTIFACT_FILTER=*arm64.AppImage" >> $env:GITHUB_ENV
          "ARTIFACT_NAME=hstwb.imager.artifact-file.linux-arm64" >> $env:GITHUB_ENV
          $artifactName='HstWB Imager ${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }} Linux ARM64.AppImage'
          "$artifactName" > hstwb.imager.artifact-name.linux-arm64.txt
          "ARTIFACT_FILENAME=$artifactName" >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest' && matrix.target == 'linux-arm64'

      - name: Update Electron manifest version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/electron.manifest.json', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/electron.manifest.json') -replace '0.1.0', '${{ env.BUILD_VERSION }}'))

      - name: Update package json version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/ClientApp/package.json', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/ClientApp/package.json') -replace '0.1.0', '${{ env.BUILD_VERSION }}'))

      - name: Update index html version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/ClientApp/public/index.html', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/ClientApp/public/index.html') -replace '0.1.0', '${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }}'))

      - name: Update constants version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/ClientApp/src/Constants.js', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/ClientApp/src/Constants.js') -replace '0.1.0', '${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }}'))

      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore tool
        working-directory: ./src
        shell: pwsh
        run: dotnet tool restore

      - name: Electronize build
        working-directory: ./src
        shell: pwsh
        run: |
          cd HstWbInstaller.Imager.GuiApp
          dotnet electronize build /target custom "${{ env.TARGET }}" /electron-arch ${{ env.ELECTRON_ARCH }}

      - name: Set artifact path
        shell: pwsh
        run: |
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '${{ env.ARTIFACT_FILTER }}' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_FILENAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_FILENAME }}') >> $env:GITHUB_ENV

      - name: Upload artifact file
        uses: actions/upload-artifact@v2
        with:
          name: hstwb.imager.artifact-file.${{ matrix.target }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Upload artifact name
        uses: actions/upload-artifact@v2
        with:
          name: hstwb.imager.artifact-name.${{ matrix.target }}
          path: hstwb.imager.artifact-name.${{ matrix.target }}.txt

      - name: Upload release name
        uses: actions/upload-artifact@v2
        with:
          name: hstwb.imager.release-name
          path: hstwb.imager.release-name.txt
        if: matrix.os == 'windows-latest'

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download Windows 64-bit artifact file
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-file.win-x64

      - name: Download Windows 64-bit artifact name
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-name.win-x64

      - name: Download macOS 64-bit artifact file
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-file.osx-x64

      - name: Download macOS 64-bit artifact name
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-name.osx-x64

      - name: Download Linux 64-bit artifact file
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-file.linux-x64

      - name: Download Linux 64-bit artifact name
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-name.linux-x64

      - name: Download Linux ARM64 artifact file
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-file.linux-arm64

      - name: Download Linux ARM64 artifact name
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.artifact-name.linux-arm64

      - name: Download release name
        uses: actions/download-artifact@v2
        with:
          name: hstwb.imager.release-name
  
      - name: Set release and artifact names 
        shell: pwsh
        run: |
          "RELEASE_NAME={0}" -f (gc hstwb.imager.release-name.txt) >> $env:GITHUB_ENV
          "ARTIFACT_NAME_WIN_X64={0}" -f (gc hstwb.imager.artifact-name.win-x64.txt) >> $env:GITHUB_ENV
          "ARTIFACT_NAME_OSX_X64={0}" -f (gc hstwb.imager.artifact-name.osx-x64.txt) >> $env:GITHUB_ENV
          "ARTIFACT_NAME_LINUX_X64={0}" -f (gc hstwb.imager.artifact-name.linux-x64.txt) >> $env:GITHUB_ENV
          "ARTIFACT_NAME_LINUX_ARM64={0}" -f (gc hstwb.imager.artifact-name.linux-arm64.txt) >> $env:GITHUB_ENV

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: true
          release_name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ github.ref }}
          body: Prerelease of ${{ env.RELEASE_NAME }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload Windows 64-bit artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_NAME_WIN_X64 }}
          asset_name: ${{ env.ARTIFACT_NAME_WIN_X64 }}
          asset_content_type: 'application/octet-stream'

      - name: Upload macOS 64-bit artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_NAME_OSX_X64 }}
          asset_name: ${{ env.ARTIFACT_NAME_OSX_X64 }}
          asset_content_type: 'application/octet-stream'

      - name: Upload Linux 64-bit artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_NAME_LINUX_X64 }}
          asset_name: ${{ env.ARTIFACT_NAME_LINUX_X64 }}
          asset_content_type: 'application/octet-stream'

      - name: Upload Linux ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.ARTIFACT_NAME_LINUX_ARM64 }}
          asset_name: ${{ env.ARTIFACT_NAME_LINUX_ARM64 }}
          asset_content_type: 'application/octet-stream'