# This is a basic workflow to help you get started with Actions

name: Prerelease

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on: [workflow_dispatch]

# default environment variables
env:
  TARGET: 'win'
  ARTIFACT: './src/HstWbInstaller.Imager.GuiApp/bin/Desktop/HstWbInstaller.Imager.GuiApp Setup 1.0.0.exe'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set windows release
        run: |
          echo "TARGET=win" >> $GITHUB_ENV
          echo "ARTIFACT=./src/HstWbInstaller.Imager.GuiApp/bin/Desktop/HstWbInstaller.Imager.GuiApp Setup 1.0.0.exe" >> $GITHUB_ENV
        if: matrix.os == 'windows-latest'
        
      - name: Set version
        run: echo "BUILD_VERSION=0.1.$(git rev-list --count HEAD)" >> $GITHUB_ENV

      - name: Electron manifest version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "\"buildVersion\": \"0.1.0\""
          replace: "\"buildVersion\": \"${{ env.BUILD_VERSION }}\""
          include: "**/HstWbInstaller.Imager.GuiApp/electron.manifest.json"

      - name: Package json version
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "\"version\": \"0.1.0\""
          replace: "\"version\": \"${{ env.BUILD_VERSION }}\""
          include: "**/HstWbInstaller.Imager.GuiApp/ClientApp/package.json"

      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore tool
        working-directory: ./src
        run: dotnet tool restore

      - name: Electronize build
        working-directory: ./src
        run: |
          cd HstWbInstaller.Imager.GuiApp
          dotnet electronize build /target ${{ env.TARGET }}

      - name: List output files
        run: |
          dir "./src/HstWbInstaller.Imager.GuiApp/bin/Desktop"