# This is a basic workflow to help you get started with Actions

name: Prerelease

# Controls when the workflow will run
# Allows you to run this workflow manually from the Actions tab
on: [workflow_dispatch]

# default environment variables
env:
  TARGET: 'win'
  ARTIFACT_FILTER: '*.exe'
  ARTIFACT_NAME: 'HstWB Imager 0.1.0 Windows.exe'
  ARTIFACT_NAME_WINDOWS: 'HstWB Imager 0.1.0 Windows.exe'
  ARTIFACT_NAME_MACOS: 'HstWB Imager 0.1.0 macOS.dmg'
  ARTIFACT_NAME_LINUX: 'HstWB Imager 0.1.0 Linux.AppImage'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: win
          - os: macos-latest
            target: osx
          - os: ubuntu-latest
            target: linux

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set version
        working-directory: ./src
        shell: pwsh
        run: |
          "BUILD_VERSION=0.9.{0}" -f (git rev-list --count $env:GITHUB_REF) >> $env:GITHUB_ENV
          "BUILD_VERSION_SHA={0}" -f (git log --pretty=format:'%h' -n 1 $env:GITHUB_REF) >> $env:GITHUB_ENV

      - name: Show version
        shell: pwsh
        run: |
          "BUILD_VERSION: ${{ env.BUILD_VERSION }}"
          "BUILD_VERSION_SHA: ${{ env.BUILD_VERSION_SHA }}"

      - name: Set Windows target
        shell: pwsh
        run: |
          "TARGET=win" >> $env:GITHUB_ENV
          "${{ env.BUILD_VERSION }}-imager" > hstwb.imager.release-tag.txt
          "HstWB Imager v${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }}" > hstwb.imager.release-version.txt
        if: matrix.os == 'windows-latest'

      - name: Set macOS target
        shell: pwsh
        run: |
          "TARGET=osx" >> $env:GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Set Linux target
        shell: pwsh
        run: |
          "TARGET=linux" >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Update Electron manifest version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/electron.manifest.json', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/electron.manifest.json') -replace '0.1.0', '${{ env.BUILD_VERSION }}'))

      - name: Update package json version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/ClientApp/package.json', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/ClientApp/package.json') -replace '0.1.0', '${{ env.BUILD_VERSION }}'))

      - name: Update index html version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/ClientApp/public/index.html', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/ClientApp/public/index.html') -replace '0.1.0', '${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }}'))

      - name: Update constants version
        shell: pwsh
        working-directory: ./src
        run: |
          [System.IO.File]::WriteAllText('HstWbInstaller.Imager.GuiApp/ClientApp/src/Constants.js', ([System.IO.File]::ReadAllText('HstWbInstaller.Imager.GuiApp/ClientApp/src/Constants.js') -replace '0.1.0', '${{ env.BUILD_VERSION }}-${{ env.BUILD_VERSION_SHA }}'))

      - name: Setup .NET Core 5.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Restore tool
        working-directory: ./src
        shell: pwsh
        run: dotnet tool restore

      - name: Electronize build
        working-directory: ./src
        shell: pwsh
        run: |
          cd HstWbInstaller.Imager.GuiApp
          dotnet electronize build /target ${{ env.TARGET }}

      # upload release tag
      - name: Upload release tag artifact
        uses: actions/upload-artifact@v2
        with:
          name: hstwb.imager.release-tag
          path: hstwb.imager.release-tag.txt
        if: matrix.os == 'windows-latest'

      # upload release version
      - name: Upload release version artifact
        uses: actions/upload-artifact@v2
        with:
          name: hstwb.imager.release-version
          path: hstwb.imager.release-version.txt
        if: matrix.os == 'windows-latest'

      # windows nsis
      - name: Set Windows 64-bit nsis artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.win-x64.exe'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*.exe' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Upload Windows 64-bit nsis artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'windows-latest'

      # windows 64-bit zip
      - name: Set Windows 64-bit zip artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.win-x64.zip'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*.zip' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'windows-latest'

      - name: Upload Windows 64-bit zip artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'windows-latest'

      # macos 64-bit dmg
      - name: Set macOS 64-bit dmg artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.osx-x64.dmg'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*.dmg' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'macos-latest'

      - name: Upload macOS 64-bit dmg artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'macos-latest'

      # linux 64-bit appimage
      - name: Set Linux 64-bit appimage artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.linux-x64.AppImage'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*${{ env.BUILD_VERSION }}.AppImage' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Linux 64-bit appimage artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'ubuntu-latest'

      # linux arm64 appimage
      - name: Set Linux arm64 appimage artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.linux-arm64.AppImage'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*${{ env.BUILD_VERSION }}-arm64.AppImage' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Linux 64-bit appimage artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'ubuntu-latest'

      # linux 64-bit deb
      - name: Set Linux 64-bit deb artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.linux-x64.deb'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*${{ env.BUILD_VERSION }}_amd64.deb' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Linux 64-bit deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'ubuntu-latest'

      # linux arm64 deb
      - name: Set Linux arm64 deb artifact
        shell: pwsh
        run: |
          "ARTIFACT_NAME='hstwb-imager.linux-arm64.deb'" >> $env:GITHUB_ENV
          $artifactFile=(gci './src/HstWbInstaller.Imager.GuiApp/bin/Desktop' -Filter '*${{ env.BUILD_VERSION }}_arm64.deb' | Select-Object -First 1).FullName
          Rename-Item $artifactFile -NewName '${{ env.ARTIFACT_NAME }}'
          "ARTIFACT_PATH={0}" -f (Join-Path (Split-Path $artifactFile -Parent) -ChildPath '${{ env.ARTIFACT_NAME }}') >> $env:GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - name: Upload Linux arm64 deb artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}
        if: matrix.os == 'ubuntu-latest'

  publish:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download release tag artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.release-tag

      - name: Download release version artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.release-version
      
        # windows
      - name: Download Windows 64-bit nsis artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.win-x64.exe

      - name: Download Windows 64-bit zip artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.win-x64.zip

        # macos
      - name: Download macOS 64-bit dmg artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.osx-x64.dmg

        # linux
      - name: Download Linux 64-bit appimage artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.linux-x64.AppImage

      - name: Download Linux arm64-bit appimage artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.linux-arm64.AppImage

      - name: Download Linux 64-bit deb artifact
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.linux-x64.deb

      - name: Download Linux ARM64 artifact file
        uses: actions/download-artifact@v2
        with:
          name: hstwb-imager.linux-arm64.deb

      - name: Set release version
        shell: pwsh
        run: |
          "RELEASE_TAG={0}" -f (gc hstwb.imager.release-tag.txt) >> $env:GITHUB_ENV
          "RELEASE_VERSION={0}" -f (gc hstwb.imager.release-version.txt) >> $env:GITHUB_ENV

      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: true
          release_name: ${{ env.RELEASE_VERSION }}
          tag_name: ${{ env.RELEASE_TAG }}
          body: Prerelease of ${{ env.RELEASE_VERSION }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

        # windows
      - name: Upload Windows 64-bit nsis artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.win-x64.exe
          asset_name: '${{ env.RELEASE_VERSION }} Windows 64-bit.exe'
          asset_content_type: 'application/octet-stream'

      - name: Upload Windows 64-bit zip artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.win-x64.zip
          asset_name: '${{ env.RELEASE_VERSION }} Windows 64-bit.zip'
          asset_content_type: 'application/octet-stream'

        # macos
      - name: Upload macOS 64-bit dmg artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.osx-x64.dmg
          asset_name: '${{ env.RELEASE_VERSION }} macOS 64-bit.dmg'
          asset_content_type: 'application/octet-stream'

        # linux
      - name: Upload Linux 64-bit appimage artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.linux-x64.AppImage
          asset_name: '${{ env.RELEASE_VERSION }} Linux 64-bit.AppImage'
          asset_content_type: 'application/octet-stream'

      - name: Upload Linux arm64 appimage artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.linux-arm64.AppImage
          asset_name: '${{ env.RELEASE_VERSION }} Linux ARM64.AppImage'
          asset_content_type: 'application/octet-stream'
          
      - name: Upload Linux 64-bit deb artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.linux-x64.deb
          asset_name: '${{ env.RELEASE_VERSION }} Linux 64-bit.deb'
          asset_content_type: 'application/octet-stream'

      - name: Upload Linux arm64 deb artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: hstwb-imager.linux-arm64.deb
          asset_name: '${{ env.RELEASE_VERSION }} Linux ARM64.deb'
          asset_content_type: 'application/octet-stream'